### ISSUE TITLE
yvm use on version that is invalid/not installed crash'es yvm

### ISSUE THREAD

**Issue by jakebolam** [tophat/yvm#188]
**Describe the bug**
yvm use crashed when version is not installed

**To Reproduce**
```
yvm use v1.9.5
webpack:///./src/yvm.js?:1
throw new Error("Module build failed (from ./node_modules/babel-loader/lib/index.js):\nTypeError: /code/yvm/src/yvm.js: Duplicate declaration \"version\"\n\u001b[0m \u001b[90m 93 | \u001b[39m  \u001b[33m.\u001b[39mdescription(\u001b[32m'Internal command: Sets default fallback yarn version'\u001b[39m)\u001b[0m\n\u001b[0m \u001b[90m 94 | \u001b[39m  \u001b[33m.\u001b[39maction(version \u001b[33m=>\u001b[39m {\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 95 | \u001b[39m    \u001b[36mconst\u001b[39m [version] \u001b[33m=\u001b[39m getSplitVersionAndArgs(maybeVersion)\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m    | \u001b[39m           \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 96 | \u001b[39m    \u001b[36mconst\u001b[39m getNewPath \u001b[33m=\u001b[39m require(\u001b[32m'./commands/getNewPath'\u001b[39m)\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 97 | \u001b[39m    ensureVersionInstalled(version)\u001b[33m.\u001b

Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /code/yvm/src/yvm.js: Duplicate declaration "version"
  93 |   .description('Internal command: Sets default fallback yarn version')
  94 |   .action(version => {
> 95 |     const [version] = getSplitVersionAndArgs(maybeVersion);
     |            ^
  96 |     const getNewPath = require('./commands/getNewPath');
  97 |     ensureVersionInstalled(version).then(() => log.capturable(getNewPath(version)));
  98 |   });
    at File.buildCodeFrameError (/code/yvm/node_modules/@babel/core/lib/transformation/file/file.js:231:12)
    at Scope.checkBlockScopedCollisions (/code/yvm/node_modules/@babel/traverse/lib/scope/index.js:347:27)
    at Scope.registerBinding (/code/yvm/node_modules/@babel/traverse/lib/scope/index.js:506:16)
    at Scope.registerDeclaration (/code/yvm/node_modules/@babel/traverse/lib/scope/index.js:446:14)
    at Object.BlockScoped (/code/yvm/node_modules/@babel/traverse/lib/scope/index.js:189:28)
    at Object.newFn (/code/yvm/node_modules/@babel/traverse/lib/visitors.js:230:17)
    at NodePath._call (/code/yvm/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/code/yvm/node_modules/@babel/traverse/lib/path/context.js:36:14)
    at NodePath.visit (/code/yvm/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/code/yvm/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/code/yvm/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/code/yvm/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/code/yvm/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/code/yvm/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/code/yvm/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/code/yvm/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/code/yvm/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/code/yvm/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/code/yvm/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/code/yvm/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/code/yvm/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/code/yvm/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/code/yvm/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/code/yvm/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/code/yvm/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/code/yvm/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/code/yvm/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/code/yvm/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/code/yvm/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/code/yvm/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/code/yvm/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/code/yvm/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/code/yvm/node_modules/@babel/traverse/lib/index.js:94:17)
    at traverse (/code/yvm/node_modules/@babel/traverse/lib/index.js:76:12)
    at NodePath.traverse (/code/yvm/node_modules/@babel/traverse/lib/path/index.js:168:24)
    at Scope.crawl (/code/yvm/node_modules/@babel/traverse/lib/scope/index.js:686:10)
    at eval (webpack:///./src/yvm.js?:1:7)
    at Object../src/yvm.js (/code/yvm/artifacts/webpack_build/yvm.js:96:1)
    at __webpack_require__ (/code/yvm/artifacts/webpack_build/yvm.js:20:30)
    at /code/yvm/artifacts/webpack_build/yvm.js:84:18
    at Object.<anonymous> (/code/yvm/artifacts/webpack_build/yvm.js:87:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Could not get new path from yvm

> ```

**Expected behavior**
Should not crash, should output 'version' not installed


**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - YVM Release: (Latest)
 - Shell: zsh
 - Node version: v8.9.4

**Comment by jakebolam** [comment]
This can easily be handled in the get-path module in JS

**Comment by yashshah** [comment]
![image](https://user-images.githubusercontent.com/1558352/49786446-e159d180-fd49-11e8-84f9-a961ec244d1f.png)
I tried using the version that I don't have locally, and it worked fine. yvm went ahead and installed it and then started using it. Is there any step that I'm missing here?

**Comment by jakebolam** [comment]
Weird! Looks like it's working now. Thanks @yashshah
