### ISSUE TITLE
Lowest node version is actually 8

### ISSUE THREAD

**Issue by jakebolam** [tophat/yvm#289]
**Describe the bug**
Docs say 4.10.0 yvm only works on node > 8.

Using 4 or 6 results in:
```
/Users/jakebolam/.yvm/node_modules/openpgp/dist/openpgp.js:22591
      const doRead = async () => {
                           ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jakebolam/.yvm/yvm-exec.js:1:11778)
```

**To Reproduce**
```
$nvm use  v4.10.0
Now using node v6.11.5 (npm v3.10.10)
#yvm exec --version
ERROR (as above
```

```
$nvm use  v6.11.5
Now using node v4.8.0 (npm v2.15.11)
#yvm exec --version
ERROR (as above
```

**Expected behavior**
If the docs and engine say 4.10.0 then works with version 4

**Screenshots**
<img width="521" alt="screen shot 2019-01-19 at 7 55 20 am" src="https://user-images.githubusercontent.com/3534236/51426970-98563200-1bbf-11e9-8f9b-0d34dfe7bf3f.png">

**Comment by jakebolam** [comment]
Fixed in: https://github.com/tophat/yvm/commit/9f52944d0f7b635acfd26eaed6e8bbdff0c1a951
