### ISSUE TITLE
yvm version command fails with ENOENT during local development when no version exists

### ISSUE THREAD

**Issue by noahnu** [tophat/yvm#317]
**Describe the bug**

`yvm version` throws an error when using running it in local dev (not an official release, not using official install script).

**To Reproduce**
1. `make install`
2. `yvm install 1.14.0`
3. `yvm use 1.14.0`
4. `yvm version`

**Expected behavior**

According to `yarn --help` for `yarn version`:

> Outputs the version of yvm that is installed

I would expect an error message about how no official version has been installed. Either way, the stack trace is unnecessary. There is also a redundant "unable to determine" message.

**Screenshots**

```
$ yvm version
Unable to determine installed version
{ Error: ENOENT: no such file or directory, open '/Users/noah/.yvm/.version'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at yvmInstalledVersion (/Users/noah/.yvm/yvm.js:1:13601)
    at e.exports (/Users/noah/.yvm/yvm.js:1:13382)
    at Command.r.command.description.action (/Users/noah/.yvm/yvm.js:1:10756)
    at Command.listener (/Users/noah/.yvm/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/Users/noah/.yvm/node_modules/commander/index.js:654:12)
    at Command.parse (/Users/noah/.yvm/node_modules/commander/index.js:474:21)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/noah/.yvm/.version' }
Unable to determine yvm version
```

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.3
 - YVM Version: Latest build after running `make install` for hash: `3859362b749fbd4afe49fccc808b7a831ea0dcfe`
 - Shell: bash
 - Node version: v8.11.3

**Comment by iamogbz** [comment]
@noahnu thanks, feel free to open a PR for this!
